-- Automation Lab demo database schema (database `demo`)
-- GENERATED by seed/generate_seed.py (seed 20260101, fixed now 2026-09-01T09:00:00Z). Do not edit by hand:
-- change the generator and run `python seed/generate_seed.py`. All data is synthetic.

-- Re-runnable: drops every demo table first, then creates them.

DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS content_variants CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS execution_log CASCADE;
DROP TABLE IF EXISTS products_mirror CASCADE;
DROP TABLE IF EXISTS sync_state CASCADE;
DROP TABLE IF EXISTS webhook_events CASCADE;
DROP TABLE IF EXISTS uptime_state CASCADE;
DROP TABLE IF EXISTS uptime_checks CASCADE;
DROP TABLE IF EXISTS rate_history CASCADE;
DROP TABLE IF EXISTS expenses CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS leads CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS customers CASCADE;

CREATE TABLE IF NOT EXISTS customers (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id  text NOT NULL UNIQUE,
    name         text NOT NULL,
    email        text NOT NULL,
    phone        text,
    company      text,
    country      text,
    city         text,
    segment      text NOT NULL DEFAULT 'smb' CHECK (segment IN ('smb', 'mid', 'enterprise')),
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku          text NOT NULL UNIQUE,
    name         text NOT NULL,
    category     text,
    price        numeric(10,2) NOT NULL CHECK (price >= 0),
    currency     char(3) NOT NULL DEFAULT 'USD',
    stock        integer NOT NULL DEFAULT 0,
    updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number text NOT NULL UNIQUE,
    customer_id  integer NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    status       text NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending', 'paid', 'shipped', 'cancelled', 'refunded')),
    total        numeric(10,2) NOT NULL DEFAULT 0,
    currency     char(3) NOT NULL DEFAULT 'USD',
    ordered_at   timestamptz NOT NULL DEFAULT now(),
    shipped_at   timestamptz
);

CREATE TABLE IF NOT EXISTS order_items (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id   integer NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    qty          integer NOT NULL CHECK (qty > 0),
    unit_price   numeric(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS employees (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_no    text NOT NULL UNIQUE,
    full_name      text NOT NULL,
    full_name_ar   text,
    department     text NOT NULL,
    department_ar  text,
    title          text,
    email          text NOT NULL UNIQUE,
    hired_at       date NOT NULL
);

CREATE TABLE IF NOT EXISTS attendance (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id  integer NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    work_date    date NOT NULL,
    check_in     timestamptz,
    check_out    timestamptz,
    status       text NOT NULL CHECK (status IN ('present', 'late', 'absent', 'leave')),
    UNIQUE (employee_id, work_date)
);

CREATE TABLE IF NOT EXISTS tickets (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_no    text NOT NULL UNIQUE,
    customer_id  integer REFERENCES customers(id) ON DELETE SET NULL,
    channel      text NOT NULL CHECK (channel IN ('email', 'form', 'chat', 'telegram')),
    subject      text NOT NULL,
    body         text,
    category     text,
    priority     text NOT NULL DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
    status       text NOT NULL DEFAULT 'open'
                 CHECK (status IN ('open', 'triaged', 'in_progress', 'resolved', 'closed')),
    assigned_to  text,
    sla_due_at   timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now(),
    resolved_at  timestamptz
);

CREATE TABLE IF NOT EXISTS leads (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email              text NOT NULL UNIQUE,
    name               text,
    company            text,
    domain             text,
    source             text,
    score              integer NOT NULL DEFAULT 0 CHECK (score BETWEEN 0 AND 100),
    status             text NOT NULL DEFAULT 'new'
                       CHECK (status IN ('new', 'contacted', 'qualified', 'lost', 'won')),
    enriched           jsonb,
    created_at         timestamptz NOT NULL DEFAULT now(),
    last_contacted_at  timestamptz
);

CREATE TABLE IF NOT EXISTS bookings (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_ref       text NOT NULL UNIQUE,
    customer_id       integer REFERENCES customers(id) ON DELETE SET NULL,
    service           text NOT NULL,
    starts_at         timestamptz NOT NULL,
    ends_at           timestamptz NOT NULL,
    status            text NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed', 'cancelled', 'completed')),
    reminder_sent_at  timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now(),
    CHECK (ends_at > starts_at)
);

CREATE TABLE IF NOT EXISTS expenses (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant      text NOT NULL,
    amount        numeric(10,2) NOT NULL,
    currency      char(3) NOT NULL DEFAULT 'LYD',
    spent_at      timestamptz NOT NULL,
    category      text,
    receipt_file  text,
    extracted_by  text,
    raw_text      text,
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rate_history (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base        char(3) NOT NULL,
    quote       char(3) NOT NULL,
    rate        numeric(14,6) NOT NULL,
    fetched_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS uptime_checks (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target       text NOT NULL,
    url          text NOT NULL,
    status_code  integer,
    latency_ms   integer,
    ok           boolean NOT NULL,
    checked_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS uptime_state (
    target         text PRIMARY KEY,
    state          text NOT NULL DEFAULT 'up' CHECK (state IN ('up', 'warn', 'down')),
    failures       integer NOT NULL DEFAULT 0,
    since          timestamptz NOT NULL DEFAULT now(),
    last_alert_at  timestamptz
);

CREATE TABLE IF NOT EXISTS webhook_events (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id  text NOT NULL UNIQUE,
    source       text NOT NULL,
    event_type   text,
    payload      jsonb NOT NULL DEFAULT '{}'::jsonb,
    received_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sync_state (
    source       text PRIMARY KEY,
    cursor       text,
    last_run_at  timestamptz,
    rows_seen    integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS products_mirror (
    id            integer PRIMARY KEY,
    sku           text NOT NULL,
    name          text,
    price         numeric(10,2),
    stock         integer,
    content_hash  text,
    synced_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS execution_log (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id   text,
    workflow_id    text,
    workflow_name  text,
    status         text NOT NULL,
    started_at     timestamptz,
    finished_at    timestamptz,
    duration_ms    integer,
    error_message  text,
    error_node     text,
    logged_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notifications (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel   text NOT NULL,
    target    text,
    subject   text,
    body      text,
    severity  text NOT NULL DEFAULT 'info' CHECK (severity IN ('info', 'warning', 'error', 'critical')),
    sent_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS content_variants (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_title  text NOT NULL,
    platform      text NOT NULL,
    content       text NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tasks (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source      text,
    title       text NOT NULL,
    owner       text,
    due_date    date,
    done        boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS documents (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind         text NOT NULL,
    file_name    text NOT NULL,
    storage_key  text,
    meta         jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_customers_email ON customers (email);
CREATE INDEX IF NOT EXISTS idx_customers_segment ON customers (segment);
CREATE INDEX IF NOT EXISTS idx_products_category ON products (category);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders (customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_ordered_at ON orders (ordered_at);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product ON order_items (product_id);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance (work_date);
CREATE INDEX IF NOT EXISTS idx_tickets_customer ON tickets (customer_id);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets (status);
CREATE INDEX IF NOT EXISTS idx_tickets_created_at ON tickets (created_at);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads (status);
CREATE INDEX IF NOT EXISTS idx_bookings_starts_at ON bookings (starts_at);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings (status);
CREATE INDEX IF NOT EXISTS idx_expenses_spent_at ON expenses (spent_at);
CREATE INDEX IF NOT EXISTS idx_rate_history_pair ON rate_history (base, quote, fetched_at);
CREATE INDEX IF NOT EXISTS idx_uptime_checks_target ON uptime_checks (target, checked_at);
CREATE INDEX IF NOT EXISTS idx_webhook_events_source ON webhook_events (source, received_at);
CREATE INDEX IF NOT EXISTS idx_execution_log_workflow ON execution_log (workflow_id, started_at);
CREATE INDEX IF NOT EXISTS idx_execution_log_status ON execution_log (status, logged_at);
CREATE INDEX IF NOT EXISTS idx_notifications_sent_at ON notifications (sent_at);
CREATE INDEX IF NOT EXISTS idx_tasks_due ON tasks (done, due_date);
CREATE INDEX IF NOT EXISTS idx_documents_kind ON documents (kind, created_at);
