#!/usr/bin/env python
"""R01 - Data to PDF Invoice.

Config (order_number) -> one SQL query (order + customer + line items as JSON) -> HTML template (Code)
-> docgen /render/pdf -> write data/out/invoice-<no>.pdf -> [S3 upload to reports/invoices/ -> documents row]
                                                          -> [e-mail the customer with the PDF attached]
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from n8n_builder import (Workflow, catalog_id, code, cond_not_empty, email, http, if_, manual_trigger,  # noqa: E402
                         postgres_insert, postgres_query, s3_upload, set_fields, stop_error, write_file)

ORDER_SQL = """select o.order_number, o.status, o.total::float as total, o.currency, o.ordered_at, o.shipped_at,
       c.external_id as customer_external_id, c.name as customer_name, c.email as customer_email,
       c.company, c.city, c.country,
       coalesce((select json_agg(json_build_object('sku', p.sku, 'name', p.name, 'qty', i.qty,
                                                    'unit_price', i.unit_price::float,
                                                    'amount', (i.qty * i.unit_price)::float) order by i.id)
                 from order_items i join products p on p.id = i.product_id where i.order_id = o.id), '[]'::json) as items
from orders o
join customers c on c.id = o.customer_id
where o.order_number = $1"""

HTML_JS = r"""
// One order item in (with items[] from json_agg). Render a self-contained HTML invoice for docgen.
const o = $input.first().json;
const items = Array.isArray(o.items) ? o.items : JSON.parse(o.items || '[]');
const money = (n) => Number(n || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const subtotal = items.reduce((a, i) => a + Number(i.amount || 0), 0);
const vatRate = 0.0;                                   // demo: no tax; change per jurisdiction
const vat = subtotal * vatRate;
const total = subtotal + vat;
const issued = (o.ordered_at || '').slice(0, 10);
const due = new Date(new Date(o.ordered_at).getTime() + 30 * 86400000).toISOString().slice(0, 10);
const invoiceNo = 'INV-' + o.order_number.replace('ORD-', '');
const rows = items.map(i => `<tr><td>${i.sku}</td><td>${i.name}</td><td class="n">${i.qty}</td><td class="n">${money(i.unit_price)}</td><td class="n">${money(i.amount)}</td></tr>`).join('');
const html = `<!doctype html><html><head><meta charset="utf-8"><style>
body{font-family:'DejaVu Sans',sans-serif;font-size:11pt;color:#222;margin:32px}
h1{font-size:26pt;margin:0;color:#1a4d8f} .muted{color:#777} .grid{display:flex;justify-content:space-between;margin:24px 0}
table{width:100%;border-collapse:collapse;margin-top:12px} th{background:#1a4d8f;color:#fff;text-align:left;padding:6px}
td{padding:6px;border-bottom:1px solid #ddd} td.n,th.n{text-align:right} .totals td{border:0;font-weight:bold}
.badge{display:inline-block;padding:2px 8px;border-radius:4px;background:#e8f0fb;color:#1a4d8f;font-size:9pt}
footer{margin-top:40px;font-size:9pt;color:#777}
</style></head><body>
<div class="grid"><div><h1>INVOICE</h1><div class="muted">${invoiceNo} <span class="badge">${o.status}</span></div></div>
<div class="muted" style="text-align:right">Automation Lab Demo Co.<br>1 Example Street, Tripoli<br>billing@lab.local</div></div>
<div class="grid"><div><b>Bill to</b><br>${o.customer_name}<br>${o.company || ''}<br>${o.city || ''}, ${o.country || ''}<br>${o.customer_email}</div>
<div style="text-align:right"><b>Issue date</b> ${issued}<br><b>Due date</b> ${due}<br><b>Order</b> ${o.order_number}<br><b>Currency</b> ${o.currency}</div></div>
<table><thead><tr><th>SKU</th><th>Description</th><th class="n">Qty</th><th class="n">Unit price</th><th class="n">Amount</th></tr></thead>
<tbody>${rows}</tbody>
<tfoot class="totals"><tr><td colspan="4" class="n">Subtotal</td><td class="n">${money(subtotal)}</td></tr>
<tr><td colspan="4" class="n">VAT (${(vatRate * 100).toFixed(0)}%)</td><td class="n">${money(vat)}</td></tr>
<tr><td colspan="4" class="n">Total ${o.currency}</td><td class="n">${money(total)}</td></tr></tfoot></table>
<footer>Payment within 30 days. This is a synthetic demo document generated by Automation Lab (R01).</footer>
</body></html>`;
return [{ json: { invoice_no: invoiceNo, order_number: o.order_number, customer_email: o.customer_email,
                  customer_name: o.customer_name, total, currency: o.currency, items: items.length,
                  filename: `invoice-${o.order_number}.pdf`, html } }];
"""


def build() -> Workflow:
    wf = Workflow("R01", "pdf-invoice", "Data to PDF Invoice", tags=["Documents"],
                  error_workflow=catalog_id("P01"),
                  description="Turns an order into a PDF invoice via docgen, stores it in MinIO and e-mails it.")
    trg = manual_trigger(wf, "Run once (manual / CLI)")
    cfg = set_fields(wf, "Config", {"order_number": "ORD-2026-0001"})
    q = postgres_query(wf, "Load order + items", ORDER_SQL, params="={{ $json.order_number }}").always_output()
    found = if_(wf, "Order found?", [cond_not_empty("={{ $json.order_number ?? '' }}")])
    missing = stop_error(wf, "Order not found", "=R01: no order with number {{ $('Config').item.json.order_number }}")
    html = code(wf, "Build invoice HTML", HTML_JS)
    render = http(wf, "Render PDF (docgen)", "http://docgen:8090/render/pdf", method="POST",
                  json_body="={{ JSON.stringify({ html: $json.html, filename: $json.filename }) }}",
                  response="file", timeout_ms=60000).retry(3, 2000)
    save = write_file(wf, "Write PDF to data/out", "=/home/node/.n8n-files/data/out/{{ $('Build invoice HTML').item.json.filename }}")
    upload = s3_upload(wf, "Upload to MinIO (reports)", "reports",
                       "=invoices/{{ $('Build invoice HTML').item.json.filename }}").retry(3, 1000)
    doc = postgres_insert(wf, "Record document", "documents", {
        "kind": "invoice",
        "file_name": "={{ $('Build invoice HTML').item.json.filename }}",
        "storage_key": "=s3://reports/invoices/{{ $('Build invoice HTML').item.json.filename }}",
        "meta": "={{ JSON.stringify({ invoice_no: $('Build invoice HTML').item.json.invoice_no, order_number: $('Build invoice HTML').item.json.order_number, total: $('Build invoice HTML').item.json.total, currency: $('Build invoice HTML').item.json.currency, items: $('Build invoice HTML').item.json.items }) }}",
    })
    mail = email(wf, "Email invoice (Mailpit)", "={{ $('Build invoice HTML').item.json.customer_email }}",
                 "=Invoice {{ $('Build invoice HTML').item.json.invoice_no }} for order {{ $('Build invoice HTML').item.json.order_number }}",
                 html="=<p>Dear {{ $('Build invoice HTML').item.json.customer_name }},</p><p>please find attached invoice "
                      "<b>{{ $('Build invoice HTML').item.json.invoice_no }}</b> ({{ $('Build invoice HTML').item.json.currency }} "
                      "{{ $('Build invoice HTML').item.json.total.toFixed(2) }}).</p><p>Automation Lab Demo Co.</p>",
                 attachments="data").retry(3, 2000)
    wf.chain(trg, cfg, q, found)
    wf.connect(found, html, out=0)
    wf.connect(found, missing, out=1)
    wf.chain(html, render, save)
    wf.chain(save, upload, doc)
    wf.connect(save, mail)
    wf.sticky(
        "## R01 - Data -> PDF invoice\n"
        "One SQL query returns the order, the customer and the line items (as JSON). A Code node renders an HTML "
        "template, **docgen** (`/render/pdf`, WeasyPrint) turns it into a PDF.\n\n"
        "Outputs: `data/out/invoice-<order>.pdf`, MinIO `reports/invoices/`, a `documents` row and an e-mail to the "
        "customer (Mailpit) with the PDF attached.",
        pos=(-40, -330), width=620, height=210)
    return wf


if __name__ == "__main__":
    build().save()
